environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"

# Make sure we don't keep redownloading gcc every time
cache:
  - c:\gcc -> appveyor.yml
  - '%LOCALAPPDATA%\pip\Cache'

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install --upgrade -r build_requirements.txt"
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  # We need an arm-gcc compiler for testing iotile-build
  - if not exist "c:\gcc\bin" curl -L -o gcc-arm-none-eabi.zip https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-win32.zip?revision=df1b65d3-7c8d-4e82-b114-e0b6ad7c2e6d?product=GNU%20Arm%20Embedded%20Toolchain,ZIP,,Windows,7-2017-q4-major
  - if exist "gcc-arm-none-eabi.zip" unzip -o -q gcc-arm-none-eabi.zip -d c:\gcc\
  - set PATH=%PATH%;c:\gcc\bin
build: off

test_script:
  - "pwd"
  - "ls"
  - ps: tox -r
